#! /bin/bash

# Copyright (C) 2002 -2018 Red Hat, Inc.
#
# Authors:
# Than Ngo <than@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

if [ -n "$DISPLAY" -a -z "$1" ] ; then
	if [ -x /usr/share/switchdesk/switchdesk-gui.py ] ; then
		exec /usr/share/switchdesk/switchdesk-gui.py
	else
		echo "Desktop Switcher GUI is unavailable."
		echo "Please install the switchdesk-gui package or use"
		echo "switchdesk desktopname."
		exit 1
	fi
fi

exec switchdesk-helper $1
